version: '3.7'
services:
  db-builder:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BUILDER
    ports:
    - 3306:3306
    volumes:
    - db_builder:/var/lib/mysql
volumes:
  db_builder: